# Generated by Django 4.2.6 on 2024-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanName', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
                ('des', models.TextField()),
                ('status', models.CharField(max_length=225)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('endAt', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=225)),
            ],
        ),
    ]
