# Generated by Django 4.2.6 on 2024-08-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.user'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='humanName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.human'),
        ),
    ]
