# Generated by Django 4.2.6 on 2024-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_finance_user_alter_finance_humanname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='endAt',
            field=models.DateField(null=True),
        ),
    ]
